language: ruby
os: linux
dist: focal

install:
  - bundle install

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  skip_cleanup: true
  keep_history: true
  verbose: true
  local_dir: _site
  target_branch: master
  on:
    branch: source
