language: ruby
rvm:
  - 2.6.5
env:
  - JEKYLL_ENV=production
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler:1.17.2
install:
  - travis_retry bundle install
  - travis_retry bundle update
  - bundle exec jekyll build
notifications:
  email: false
