sudo: false
language: ruby
rvm:
  - 2.5.3
  - 2.6.5
env:
  - RUBY_VERSION_FOR_DEPLOY=2.6.5
  - JEKYLL_ENV=production
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
  - travis_retry bundle update
  - bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  target-branch: master
  fqdn: bandithijo.github.io
  on:
    branch: master
    rvm: $RUBY_VERSION_FOR_DEPLOY
notifications:
  email: false
