# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BanditHijo (R)-Chive
email: bandithijo@gmail.com
description: Here's where I started writing some notes that someday I will call it, a book
baseurl: "" # the subpath of your site, e.g. /blog
url: https://bandithijo.com
site: bandithijo.com

# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Makassar

# Opengraph
locale: id_ID
logo: /assets/img/logo/logo_author.png

# Google Analytics
google_analytics: UA-116004889-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at

default:
  -
    scope:
      path:
      type: posts
    values:
      layout: post

# Sitemap Generator
# Url : https://github.com/kinnetica/jekyll-plugins
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"

# Jekyll-Feed
# Url : https://github.com/jekyll/jekyll-feed
feed:
    categories:
        - blog
        - vlog
        - python

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
